### ISSUE TITLE
Images in documentation broken

### ISSUE THREAD

**Issue by leftaroundabout** [diagrams/diagrams.github.io#4]
Pretty much all of the examples in [the manual](https://diagrams.github.io/doc/manual.html) have images with hash-filenames not in [the `doc/images` folder](https://github.com/diagrams/diagrams.github.io/tree/master/doc/images).

I suppose what happened is that something changed the way the hashes are computed, the new hashes were adapted in the html pages, but the filenames of the uploaded images were not changed accordingly?

Perhaps the easiest solution is to remove all images in the repo and commit them anew.

**Comment by byorgey** [comment]
Thanks for the report!  I think the issue was that the deploy script I was using failed to *add* any new files to this repo and only committed files that had changed.  I added the new images to this repo manually, and also fixed the deploy script in https://github.com/diagrams/diagrams-doc/commit/8972ab036a175904ae5e51e3ad97bf0761916fe7 .
